In [12]:
from openalgo import api

# Initialize the API client
client = api(api_key='openalgo-api-key', host='http://127.0.0.1:5000')

# Fetch historical data for BHEL
df = client.history(
    symbol="SBIN",
    exchange="NSE",
    interval="10s",
    start_date="2024-12-17",
    end_date="2024-12-17"
)

df

                            close    high     low    open  volume
timestamp
2024-12-17 09:15:00+05:30  859.00  860.95  858.55  858.55   17877
2024-12-17 09:15:10+05:30  859.90  859.95  858.35  859.10   12087
2024-12-17 09:15:20+05:30  860.45  861.00  859.65  859.65   15394
2024-12-17 09:15:30+05:30  860.30  860.45  859.80  860.45    7734
2024-12-17 09:15:40+05:30  860.40  860.55  859.80  860.55    8407
...                           ...     ...     ...     ...     ...
2024-12-17 15:29:10+05:30  849.65  849.90  849.40  849.90    4444
2024-12-17 15:29:20+05:30  849.70  849.70  849.40  849.65    3534
2024-12-17 15:29:30+05:30  848.85  849.80  848.85  849.70   23712
2024-12-17 15:29:40+05:30  849.30  849.80  849.10  849.25    5093
2024-12-17 15:29:50+05:30  849.80  849.80  849.15  849.80    1756

[2250 rows x 5 columns]